# Generated by Django 6.1.1 on 2026-09-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_body',
            field=models.IntegerField(max_length=2000),
        ),
    ]
