# Generated by Django 6.1.1 on 2026-09-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_rename_categories_category_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_body',
            field=models.CharField(max_length=2000),
        ),
    ]
